language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - ruby-head
  - jruby-head
env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
    - rvm: jruby-19mode
    - env: "RAILS_VERSION=master"
script: rspec spec
before_install:
  - gem install bundler
